set -g fish_color_normal normal
set -g fish_color_command green
set -g fish_color_quote magenta
set -g fish_color_red red
set -g fish_color_green green
set -g fish_color_yellow yellow
set -g fish_color_blue blue
set -g fish_color_magenta magenta
set -g fish_color_cyan cyan
set -g fish_color_white white
set -g fish_color_black black
set -g fish_color_selection_bg black
set -g fish_color_selection_fg normal
set -g fish_color_search_match blue
set -g fish_color_operator normal
set -g fish_color_escape yellow
set -g fish_color_param magenta
