[colors]
base = #232136
surface = #2a273f
overlay = #393552

muted = #6e6a86
subtle = #908caa
text = #e0def4

love = #eb6f92
gold = #CC8A2D
rose = #ea9a97
pine = #3e8fb0
foam = #9ccfd8
iris = #c4a7e7

; ----------------------

[bar/main]
width = 99%
offset-x = 0.5%
background = ${colors.base}
foreground = ${colors.text}
override-redirect = true
wm-restack = i3
modules-left = i3mode i3 media
modules-center = date clock
scroll-up = i3-msg workspace prev
scroll-down = i3-msg workspace next
enable-ipc = true
tray-position = right
tray-padding = 24
tray-maxsize = 48
module-margin-left = 1
padding-right = 2
include-file = ~/.config/polybar/local.ini

; ----------------------

[module/i3]
type = internal/i3
pin-workspaces = true
show-urgent = true
strip-wsnumbers = true
format = <label-state>

label-focused = %name%
label-focused-background = ${colors.gold}
label-focused-foreground = ${colors.base}
label-focused-padding = 1

label-visible = %name%
label-visible-background = ${colors.surface}
label-visible-foreground = ${colors.text}
label-visible-padding = 1

label-unfocused = %name%
label-unfocused-background = ${colors.base}
label-unfocused-foreground = ${colors.subtle}
label-unfocused-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.love}
label-urgent-foreground = ${colors.base}
label-urgent-padding = 1

; ----------------------

[module/i3mode]
type = custom/script
exec = ~/.config/polybar/scripts/i3-modes.sh
tail = true
label = %output%

format-background = ${colors.love}
format-foreground = ${colors.base}
format-padding = 2
format-margin = 1

label-font = 2

; ----------------------

[module/date]
type = custom/script
exec = LC_TIME=pt_BR.UTF-8 date '+%a %d.%m.%Y'
interval = 60
label = %output%
label-foreground = ${colors.iris}
click-left = gsimplecal &

; ----------------------

[module/clock]
type = internal/date
interval = 1
date = %H:%M:%S
label = %date%
label-foreground = ${colors.gold}

; ----------------------

[module/keyboard]
type = custom/ipc
hook-0 = setxkbmap -query | awk '/layout:/ {print toupper($2)}'
initial = 1
label = %output%
format-prefix = "󰌓  "
format-prefix-foreground = ${colors.love}
label-foreground = ${colors.love}

; ----------------------

[module/volume]
type = custom/ipc
hook-0 = amixer get Master | awk -F'[][]' '/Left:/ { if ($4 == "off") { print "Mute" } else { print $2 } }'
initial = 1
format-prefix = "󰥛  "
format-prefix-foreground = ${colors.love}
label-foreground = ${colors.love}

; ----------------------

[module/lightness]
type = custom/ipc
hook-0 = ~/.config/i3/scripts/lightness.sh
initial = 1
label-foreground = ${colors.gold}

; ----------------------

[module/separator]
type = custom/text
content = 
content-foreground = ${colors.muted}
content-padding = 1

; ----------------------

[module/dunst]
type = custom/ipc
hook-0 = ~/.config/polybar/scripts/dunst-status.sh
initial = 1
label-foreground = ${colors.love}

; ----------------------

[module/tray]
type = internal/tray
format-margin = 0

; ----------------------

[module/media]
type = custom/script

exec = playerctl metadata --follow --format '{{artist}} - {{title}}'
tail = true

format-prefix = "  "
label = %output%
label-maxlen = 40
label-ellipsis = true
format-prefix-foreground = ${colors.muted}
format-foreground = ${colors.muted}

click-left = playerctl play-pause
click-middle = playerctl previous
click-right = playerctl next
