set -g prefix C-s

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

unbind r
bind-key C-r source-file ~/.config/tmux/tmux.conf \; display-message "tmux reloaded"

bind-key r run-shell "~/.config/tmux/scripts/rails-bin-dev.sh"  # start Rails dev server
bind-key R run-shell "~/.config/tmux/scripts/rails-project.sh"  # open Rails project layout

bind-key e run-shell "~/.config/tmux/scripts/rails-exercises.sh" # open exercises

bind-key y run-shell "~/.config/tmux/scripts/postgres-start.sh" # start Postgres
bind-key Y run-shell "~/.config/tmux/scripts/postgres-stop.sh"  # stop Postgres

