# bar {
#     status_command i3blocks
# 
#     position top
#     height 64
# 
#     tray_output primary
#     tray_padding 8
# 
#     colors {
#         background $bg0
#         statusline $fg0
#         separator  $cyan
# 
#         #                  border   bg       text
#         focused_workspace  $yellow  $yellow  $bg2
#         active_workspace   $bg2     $bg2     $fg2
#         inactive_workspace $bg1     $bg0     $fg2
#         urgent_workspace   $red     $red     $bg0
#     }
# }

# Border colors        border   bg       text     indicator  child_border
client.focused          $yellow  $yellow  $bg0     $yellow    $yellow
client.focused_inactive $bg3     $bg2     $fg2     $bg3       $bg3
client.unfocused        $bg3     $bg2     $fg3     $bg3       $bg3
client.urgent           $red     $red     $fg0     $red       $red
