## Application Launching
bindsym $mod+Return exec wezterm
# bindsym $mod+d exec --no-startup-id dmenu_run
bindsym Mod1+Tab exec --no-startup-id rofi -show drun -matching fuzzy -no-show-match -drun-display-format "{name}"
# bindsym Mod1+Tab exec --no-startup-id $HOME/.config/i3/scripts/rofi_workspace.sh
bindsym $mod+c exec --no-startup-id "rofi -show calc -modi calc -p '' -no-show-match -no-sort -no-persist-history"
bindsym $mod+Shift+p exec --no-startup-id $HOME/.config/i3/scripts/theme.sh
bindsym $mod+Mod1+p exec --no-startup-id $HOME/.config/i3/scripts/theme-check.sh
bindsym $mod+e exec nemo

## Notifications
bindsym $mod+Mod1+n exec --no-startup-id dunstctl history
bindsym $mod+Mod1+m exec --no-startup-id dunstctl close-all
bindsym $mod+Shift+n exec --no-startup-id dunstctl history-clear
bindsym $mod+Shift+m exec --no-startup-id ~/.config/i3/scripts/dunst-toggle.sh

## Screenshot
bindsym --release $mod+Shift+s exec --no-startup-id sh -c 'import png:- | tee "$HOME/Pictures/Screenshots/screenshot_$(date +"%Y%m%d_%H%M%S").png" | xclip -selection clipboard -t image/png'

## Touchpad & Mouse
bindsym $mod+Mod1+t exec --no-startup-id $HOME/.config/i3/scripts/touchpad-switch.sh
bindsym $mod+Mod1+k exec --no-startup-id $HOME/.config/i3/scripts/toggle-keyboard.sh
# bindsym $mod+Mod1+m exec --no-startup-id $HOME/.config/i3/scripts/toggle-monitor.sh

## Window Management
bindsym $mod+Tab focus next
bindsym $mod+Shift+Tab focus prev
bindsym $mod+Shift+q kill
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right
bindsym $mod+Ctrl+h split h
bindsym $mod+Ctrl+v split v
bindsym $mod+f fullscreen toggle
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+q layout toggle split
bindsym $mod+Shift+space floating toggle
bindsym $mod+Ctrl+space focus mode_toggle
bindsym $mod+a focus parent
bindsym $mod+space exec --no-startup-id $HOME/.config/i3/scripts/toggle-keyboard-lang.sh
bindsym $mod+Shift+minus move scratchpad
bindsym $mod+minus scratchpad show, floating toggle

## i3 Management
bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"
bindsym $mod+Shift+x exec i3lock -p default -c 191724

## Resize mode entry
bindsym $mod+r mode "resize"
