set $bg0      #191724
set $bg1      #1f1d2e
set $bg2      #26233a
set $bg3      #2a273f
set $bg4      #393552
set $bg5      #44415a

set $fg0      #e0def4
set $fg1      #d9d7ee
set $fg2      #908caa
set $fg3      #6e6a86

set $yellow   #f6c177
set $orange   #ea9a97
set $red      #eb6f92
set $magenta  #ebbcba
set $violet   #c4a7e7
set $blue     #9ccfd8
set $cyan     #9ccfd8
set $green    #31748f
set $gray     #6e6a86
