# Show application class instead of the window title in tabbed/stacked layouts
for_window [class=".*"] title_format "%class"
for_window [class="FFPWA-01K1GDFD8NA0690FHF4TGZD3G8"] title_format "WhatsApp"
for_window [class="FFPWA-01KW5MTD17P6M4ARP369ZREJNC"] title_format "Calendar"
for_window [class="FFPWA-01KY34S5BQGZ506A63N7QBVFBH"] title_format "Notion"
for_window [class="FFPWA-01KYJGMNBECATQ9EQXZT3Y66F6"] title_format "ChatGPT"
for_window [class="FFPWA-01KYJGN2K0GYRM99ZWYXPGDDNQ"] title_format "Claude"
for_window [class="FFPWA-01KYJGNW3SETRVKRYEYY9Y4A80"] title_format "Perplexity"
for_window [class="FFPWA-01KZ7QJ8591W5TYMWQPS80VN29"] title_format "Open WebUI"
